Department.create(name: 'Marketing')
Department.create(name: 'Information Technology')
Department.create(name: 'Sales')
Department.create(name: 'Human Resources')
Department.create(name: 'Finance')
Department.create(name: 'Events')
Department.create(name: 'Other')
